version: "3.9"  # optional since v1.27.0
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      target: runtime
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .env:/mnt/.env
